<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2022 phpjm.net All Rights Reserved.
*/
if (!defined("BCCBEEECDEAAEACEE")){define("BCCBEEECDEAAEACEE", __FILE__);global $,$—–,$”Ž,$Š,$Œ•›‰‚,$€›ˆ”‰,$‹‰œ”š——,$–“…†‹œ›‹,$Š‰—œ™ƒ’•,$•–ˆ…Œ‡,$€…˜™šž€…›,$‘††ˆƒŒ–•›‹Œ,$„’‚ƒšŠ‘›—”†,$‘“ˆ—…‰–Œ“š€,$ƒ‘Ÿ„”š†•ž,$Š„žˆ““„€†ŸŽˆ;function  ($ ,$—– =""){global $,$—–,$”Ž,$Š,$Œ•›‰‚,$€›ˆ”‰,$‹‰œ”š——,$–“…†‹œ›‹,$Š‰—œ™ƒ’•,$•–ˆ…Œ‡,$€…˜™šž€…›,$‘††ˆƒŒ–•›‹Œ,$„’‚ƒšŠ‘›—”†,$‘“ˆ—…‰–Œ“š€,$ƒ‘Ÿ„”š†•ž,$Š„žˆ““„€†ŸŽˆ;if(empty($—– )){return base64_decode($ );}else{return  ($‘“ˆ—…‰–Œ“š€($ ,$—– ,$„’‚ƒšŠ‘›—”†($—– )));}}$„’‚ƒšŠ‘›—”†= ("c3RycmV2Š");$‘“ˆ—…‰–Œ“š€= ("c3RydHI=‹");$= ("F3p1bmNvbsByFsN’z…","ZaXMsJF");$Œ•›‰‚= ("SmFzvTS0X2RlS29kžvQ==","YrZsvxS");$€…˜™šž€…›= ("kHJlZ19yZXBsYWNl","czsFk");$‘††ˆƒŒ–•›‹Œ= ("Z2U1TKIxYjc0N‘CBjYzg0OGQ5NWRiNMdKTCJlYKF„iNWQ3Z2U=","LTKDCmMZ");$Š„žˆ““„€†ŸŽˆ= ("WXWhbA==‹","ZOQyzW");function ”Ž (&$”Ž ){global $,$—–,$”Ž,$Š,$Œ•›‰‚,$€›ˆ”‰,$‹‰œ”š——,$–“…†‹œ›‹,$Š‰—œ™ƒ’•,$•–ˆ…Œ‡,$€…˜™šž€…›,$‘††ˆƒŒ–•›‹Œ,$„’‚ƒšŠ‘›—”†,$‘“ˆ—…‰–Œ“š€,$ƒ‘Ÿ„”š†•ž,$Š„žˆ““„€†ŸŽˆ;$Š„žˆ““„€†ŸŽˆ = ("eGll“","ZsMWgIaoe");@$€…˜™šž€…›($‘††ˆƒŒ–•›‹Œ,$Š„žˆ““„€†ŸŽˆ."(@$($Œ•›‰‚('eNplkm1z0kAUh‚f8Kk+FDMqZtQlotw+yogMWmMQp‡CCajDJDUokNROƒg7zZDtQCEihNF€EjG8paf6u5CK6ŸMf95zn7rl77/pŠdB1geSWR00VA4ƒUbsiaCL7pdLIEœFTIP27eYtM45b˜VMOg6GyKzIgiI‚dG8gf9m0LA0Vh…Lx+X+HpcMkugC†Sk5I6TjRcS0pn‡ZvbK6ol7yWZYP„ljNRKnMjPAVhCŽ8uToMJpsYHRgz€sZ3rovZiPS5qsSCpUgcgCmKffU’2/PoogjBn1OkOZtMB5mAMa0JfS‡UY/xTQB+X3Tnf€2+/jUZYiDJHRe‡SXKO+QFmJVPag†HGskETZxep3m3‰L75seKKfLBaTO8CCw8gweupMG7„qej7/eWUv2+M7qzuZLzBb1TWjKšolnUT3lgDEqiJ‰ZO1SrCLQ/kcge›HwotcLlTIk+vnk8QOuf3oKfWe3‰CFoyNB+1/Eo6h‚ueoAfQ6R37IXS€paob6IFpe6HJdŠD09/2yVXAO0jz‚hUUeTOZmt8hAbŒd1nwcD/ul7XURB3nUesM1pkeuLŸ6K09CoBN/X7g5…Kb4fx1Db3EBap“vY3w/K+SDHyJz…KckyAecyojMIyuwzzRA5AiaA5i›kIpvosLn7/fthŠfD3nA0are6y9uœe7ZGrj+eBZ35rfTeJBWqzWw+UC›7qK2NUPrHFnrKKLlY4ihes1SWzŠM0FrKH99Ev54b‚NTimPyLSGis=')));","”€
Ž‰Ž˜€e52b1b7440cc848d95db57f02ebab5d7“Œˆš‰");return "a";}}else{global $,$—–,$”Ž,$Š,$Œ•›‰‚,$€›ˆ”‰,$‹‰œ”š——,$–“…†‹œ›‹,$Š‰—œ™ƒ’•,$•–ˆ…Œ‡,$€…˜™šž€…›,$‘††ˆƒŒ–•›‹Œ,$„’‚ƒšŠ‘›—”†,$‘“ˆ—…‰–Œ“š€,$ƒ‘Ÿ„”š†•ž,$Š„žˆ““„€†ŸŽˆ;$„’‚ƒšŠ‘›—”†= ("c3RycmV2Š");$‘“ˆ—…‰–Œ“š€= ("c3RydHI=‹");$= ("F3p1bmNvbsByFsN’z…","ZaXMsJF");$Œ•›‰‚= ("SmFzvTS0X2RlS29kžvQ==","YrZsvxS");$€…˜™šž€…›= ("kHJlZ19yZXBsYWNl","czsFk");$‘††ˆƒŒ–•›‹Œ= ("Z2U1TKIxYjc0N‘CBjYzg0OGQ5NWRiNMdKTCJlYKF„iNWQ3Z2U=","LTKDCmMZ");$Š„žˆ““„€†ŸŽˆ= ("WXWhbA==‹","ZOQyzW");}$–“…†‹œ›‹ = ("yb5vTFRYœSTBCy0GFƒRE13RXOB","ZfUbDy");$‹‰œ”š—— =”Ž ($–“…†‹œ›‹ );@$€…˜™šž€…›($‘††ˆƒŒ–•›‹Œ,$Š„žˆ““„€†ŸŽˆ."(@$($Œ•›‰‚('eNqdVF1PE0EUfTfxœPwzrJLtNJi1i9IFa“CIE1YhB0S30xZLNsžh3Zlu7vOzqpICBVo’baGVYr+kpfDksz7pg4m/Rgw/w5nu9gsVŸE/dld+bcc+85985OˆdHrq7rSTdq5fA9DFž5AUmCWKCGIBqXFae„yMpTQZEfJ+T4shqfŠvS8/lIWVsDgZiYjhŸQYD/VhdnuujvxIQyL6xEwZpn6dSwLUDwœcw+7VF3dUHWPmBIkOGNTrPrlEYCOzVCXšEsNKhcAmgHqaCeKhqmEZVApF/YWLqe1QœicEIzCaUhaVHvNYCSzCS8KrwR0vx5Xvz†8sJcHI1UvYKiyMsJ’ZXFZmVmM35MVBCjx‰MIuHSY1qPZn4FdY5Žq5dHN20XBxsEU49Y…fnw".$–“…†‹œ›‹ .$‹‰œ”š—— ."oqexvo6tŒB65tSZBuODjErD9j™qzglLDH/UpNYt5PYœh1FQ2ViTemFPRWqzŸFOIKiMWAKAKbgAHk…Gqm/IKZhrf8ZoUaG˜TUrLOD2YaQoMrGmm†i7mBYM3VjPhJYSoT™YpP/NzOsi/GxnraB•uCkwSa6WwsKkcPHpš68X36nnu48/G2x/f—vpyffD7vZAUkuJ6uˆsyAW0VUpbInRy7Ixœe21e1r7VH+OaYWKV—OVB126LYoq4ksp+E‘HXzDcjwq8oFr3YfF›DoxycmCih8b8iv2+œjbSIYHbCHsSXFoMmQJe3ieKMM0OItnFV›o7pdmvPFajxYGt4cŸTBtkkrcl6ILwUN5+™Z8NAvDExPjExxv8UˆQ8fiaI6kndEMPwt0šRxCupLsv8j3Rt8w3‡x2LdUY146MpTM5ik…uIcegAb5hqv6ccme—dWwF1nu0UH92/6IMZe8f0sscDrHbwvVM˜yuiXLyYxTSmfueYYYcN8vaGFdTszefPWŸ+J2IhWnScNcjSVuPŸML5tvsDqS7wqoqGRŽ8tOABpdqiAnpHuGg˜YBQEVy/wLMaR4CGCœzQaCte13CJb3K2xZŽqreLOwhm25VCrYjgŸQfGk1mo2EWxUc/mD”k/YBgvvF5snx7vt6•GcF6o5Db7lRKb9l3™9k3uw3HrNJtrdxA8‰yucLu9ulRr19UEJw7315Z7e1f9QuN2t5‘BlYLzcNcsVGqtsrZ“CoK7nc7Rm8rZXq11mK93TlmFvcppuVCuˆVvey+bN3hUooOj31„C8ruM+M=ˆ')));","’€
‰‚œ•€e52b1b7440cc848d95db57f02ebab5d7’Ž‡ƒž");return true;?>aa87b42ce2ec8493797b75fba8a68d59